# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 권기석
title: 게임 클라이언트 프로그래머
email: soorison@naver.com
website: https://soorison-ks.tistory.com/

# Dark Mode (true/false/never)
darkmode: true

# Social links
# twitter_username: facespics
github_username:  Kwon-Kiseok
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: Notion Page
  icon: fas fa-globe
  url: https://absorbing-authority-051.notion.site/73dd935f586a468cbe805516bafd40b9?pvs=4
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: 소개
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  2년차 모바일 게임 클라이언트 개발자로, Unity를 이용한 여러 모바일 게임 제작 경험이 있습니다. 
  주로 4인 팀에서 기획자와 1:1로 작업하며, 기획 단계부터 주도적으로 참여했습니다. 
  프로토타입 개발부터 광고 테스트 영상 제작, 게임 개발까지 다양한 프로젝트를 진행했습니다.

  개발한 내용에 대한 재검증과 최적화를 통한 개선을 중요시하며, 문제 발생 시 또는 추가 개선점이 생각났을 때 기록을 통해 복기하고 더 좋은 방향으로 개선하는 일을 즐깁니다. 
  기능 구현에 그치지 않고 개발 역량을 향상시키는 데 항상 노력합니다.

  개발 뿐만 아니라 아트와 사업 파트와의 소통도 중요시하며, 모르는 부분에 대한 질문, 의견 제시와 수용 등을 통해 항상 적극적으로 팀워크를 유지하고자 합니다. 
  게임 개발에서의 동료들과의 커뮤니케이션의 중요성을 인지하고 있으며, 이에 대한 자신감을 가지고 있습니다.

content:
#  - title: Projects # Title for the section
#    layout: list # Type of content section (list/text)
#    content:
#      - layout: top-middle
#        title: Super awesome project
#        link: github.com/sproogen
#        # link_text: Project Website
#        additional_links:
#          - title:  sproogen/modern-resume-theme
#            icon: fab fa-github
#            url: github.com/sproogen/modern-resume-theme
#          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
#          #   icon: fab fa-github
#          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
#        quote: >
#          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
#        description: | # this will include new lines to allow paragraphs
#          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: 경력 # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 알로하팩토리
        link: https://www.aloha-corp.com/
        # link_text: boringcompany.com
        sub_title: 모바일 게임 클라이언트 개발자
        caption: 2022.09 - 2024.06
        quote: >
          Unity엔진과 자체 데이터 분석을 활용하는 모바일 게임 회사
        description: | # this will include new lines to allow paragraphs
            모바일 게임 클라이언트 개발자로 근무하면서 6가지 정도의 사내 모바일 게임 제작 프로젝트의 개발을 담당하였습니다.
            기획자와 2인을 팀을 맺어 프로토타입부터 내부에서 정한 여러 지표 확인 테스트 단계 별로 긴밀하게 제작하고 테스트 및 배포한 경험이 있습니다.
            
            Unity엔진을 주로 활용하였으며 게임의 구조 설계부터 시작하여 게임 컨텐츠 개발, 최적화 및 테스트 빌드 배포 등의 업무를 진행하였습니다.
            잦은 테스트를 해봐야 하는 만큼 촉박한 일정의 업무들이 많았지만 무리없이 소화해낼 수 있는 역량을 키울 수 있는 경험을 했습니다.

  - title: 프로젝트 # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Idle Dragon Tycoon
        link: https://youtu.be/66APK31KRwk?si=MVznD1FWrHrQvEai
        link_text: 게임 영상 링크
        sub_title: C#, Unity, UniRx, Zenject, UniTask, Firebase
        caption: 2024.01 - 2024.04
        quote: >
          드래곤 육성 시뮬레이션 게임
        description: | # this will include new lines to allow paragraphs
            - 직전 프로젝트인 'Goose Valley' 프로젝트의 리소스 및 주요 기획을 개선하여 개발한 게임
            - 기획자 1인, 개발자 1인으로 구성하여 개발
            - UniTask를 사용해보면서 기존에 코루틴으로 작업했던 부분들의 비용감소와 가독성을 개선
            - 조작감 개선 및 튜토리얼 폴리시, 애니메이션 개선의 반복 등을 통해 D1 테스트 시 유저 이탈율 개선
            - Cinemmachine을 활용한 여러 카메라 연출 적용 및 Tweening 애니메이션을 통한 게임 비주얼 향상

      - layout: left
        title: Goose Valley
        link: https://youtu.be/QMTon52vfA4?si=MwfZnzlZr6B3J8uA
        link_text: 게임 영상 링크
        sub_title: C#, Unity, UniRx, Zenject, Firebase
        caption: 2023.07 - 2023.12
        quote: >
          거위의 레스토랑 경영 타이쿤 게임
        description: | # this will include new lines to allow paragraphs
            - 트리플라의 '고양이 스낵바', Lessmore UG의 'Eatventure'를 레퍼런스로 한 3D 방치형 경영 시뮬레이션 게임
            - 기획자 1인, 개발자 1인으로 구성하여 개발
            - NavMeshAgent와 타일맵을 활용하여 8방향 이동 및 길찾기 시스템을 구현
            - UniRx와 옵저버 패턴을 위주로 활용하여 손님의 주문 및 판매 등의 게임 플레이 시스템 개발

      - layout: left
        title: Pig Pioneer
        link: https://youtu.be/wrRsG4RdSOo?si=11yKHpqElESl3_MZ
        link_text: 게임 영상 링크
        sub_title: C#, Unity, UniRx, Zenject, Firebase
        caption: 2022.11 - 2023.03, 2023.06 - 2023.07
        quote: >
          돼지들의 발전기 전략 타이쿤 게임
        description: | # this will include new lines to allow paragraphs
            - 'Reactor - Energy Sector Tycoon'을 레퍼런스로 한 입사 후 첫 메인 개발 전담 프로젝트
            - 기획자 1인, 개발자 1인으로 구성하여 개발
            - 타일맵과 UI 조작을 기반으로 한 건물의 생성-배치-파괴 시스템 개발
            - UniRx, Zenject를 기반으로 한 게임 프레임워크 개발 및 활용
            - 카드 강화 시스템 및 가챠 확률 시스템 등의 BM 컨텐츠 개발
  
  - title: 교육
    layout: list
    content:  # this will include new lines to allow paragraphs
      - layout: left
        title: 경일 게임 아카데미
        # link: https://youtu.be/66APK31KRwk?si=MVznD1FWrHrQvEai
        # link_text: 게임 영상 링크
        # sub_title: C#, Unity, UniRx, Zenject, UniTask, Firebase
        caption: 2022.02 - 2022.08
        # quote: >
        #  드래곤 육성 시뮬레이션 게임
        description: | # this will include new lines to allow paragraphs
            프로그래밍 파트 - 유니티 엔진 국비지원 캠프 프로그램 참여

      - layout: left
        title: 삼성 청년 SW 아카데미 SSAFY 6기
        # link: https://youtu.be/66APK31KRwk?si=MVznD1FWrHrQvEai
        # link_text: 게임 영상 링크
        # sub_title: C#, Unity, UniRx, Zenject, UniTask, Firebase
        caption: 2021.07 - 2021.12
        # quote: >
        #  드래곤 육성 시뮬레이션 게임
        description: | # this will include new lines to allow paragraphs
            삼성전자x고용노동부 SW 교육 및 청년 취업 프로그램 참여

      - layout: left
        title: 호서대학교
        # link: https://youtu.be/66APK31KRwk?si=MVznD1FWrHrQvEai
        # link_text: 게임 영상 링크
        sub_title: 게임학전공
        caption: 2014.03 - 2021.02
        # quote: >
        #  드래곤 육성 시뮬레이션 게임
        description: | # this will include new lines to allow paragraphs
            현 게임소프트웨어학과, 수석 졸업(최종학점 4.02 / 4.5)

  - title: 기술
    layout: text
    content: | # this will include new lines to allow paragraphs
      학습하고 주로 사용한 기술들입니다:
      - C#
      - C/C++
      - Unity
      - Firebase기반 SDK
      - UniRx
      - Zenject
      - UniTask
      - DoTween

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
